// Code generated by scripts/build_li_district. DO NOT EDIT.
// Source: 內政部 村里界 (dataset 7441).
// 雙北 (台北市 + 新北市) only.
//
// 初始 stub: 跑下列指令重建 (CSV 不入 repo):
//
//	go run ./scripts/build_li_district \
//	    -csv /path/to/villages.csv \
//	    -out app/services/ai/tools/eco/li_to_district_data.go
//
// 在表填好之前, resolveDistrict 會 fallback 到 address 含「XX區」, 仍可基本工作。
package eco

func init() {
	// liToDistrict already declared (and pre-initialized to empty) in li_to_district.go.
	// codegen 會把這段整個覆寫成完整 map。
}
