// Build a Go map of 雙北 (里 → 區) from a 政府資料開放平臺 CSV
// (推薦 dataset 7441「村里行政區域圖」屬性表 CSV).
//
// 一次性 codegen — CSV 不入 repo, 由開發者本機跑後將產出
// li_to_district_data.go 一起 commit.
//
// 使用範例:
//
//	go run ./scripts/build_li_district \
//	    -csv /tmp/villages.csv \
//	    -out app/services/ai/tools/eco/li_to_district_data.go
//
// CSV 預設欄位名 (內政部 7441 標準): COUNTYNAME / TOWNNAME / VILLNAME
// 若你的 CSV 是中文表頭, 可用 -county/-town/-village flag 指定:
//
//	go run ./scripts/build_li_district -csv x.csv \
//	    -county 縣市 -town 鄉鎮市區 -village 村里
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strings"
)

func main() {
	var (
		csvPath   = flag.String("csv", "", "path to source CSV (required)")
		outPath   = flag.String("out", "app/services/ai/tools/eco/li_to_district_data.go", "output Go file")
		colCounty = flag.String("county", "COUNTYNAME", "CSV column for 縣市")
		colTown   = flag.String("town", "TOWNNAME", "CSV column for 鄉鎮市區")
		colVill   = flag.String("village", "VILLNAME", "CSV column for 村里")
	)
	flag.Parse()
	if *csvPath == "" {
		log.Fatal("-csv is required")
	}

	rows, err := readCSV(*csvPath)
	if err != nil {
		log.Fatalf("read csv: %v", err)
	}
	if len(rows) < 2 {
		log.Fatalf("csv has no data rows")
	}

	header := rows[0]
	idxCounty := indexOf(header, *colCounty)
	idxTown := indexOf(header, *colTown)
	idxVill := indexOf(header, *colVill)
	if idxCounty < 0 || idxTown < 0 || idxVill < 0 {
		log.Fatalf("missing columns; header=%v want county=%q town=%q village=%q",
			header, *colCounty, *colTown, *colVill)
	}

	type entry struct{ city, li, district string }
	var entries []entry
	for _, r := range rows[1:] {
		if len(r) <= idxCounty || len(r) <= idxTown || len(r) <= idxVill {
			continue
		}
		county := strings.TrimSpace(r[idxCounty])
		town := strings.TrimSpace(r[idxTown])
		vill := strings.TrimSpace(r[idxVill])
		// 雙北 only
		if county != "臺北市" && county != "台北市" && county != "新北市" {
			continue
		}
		// town 必須是「XX區」
		if !strings.HasSuffix(town, "區") {
			continue
		}
		// 同時保留「臺/台」兩種 city 形式 — park 資料用「臺」, 其他來源可能用「台」
		entries = append(entries,
			entry{city: normalizeCity(county, "臺"), li: vill, district: town},
			entry{city: normalizeCity(county, "台"), li: vill, district: town},
		)
	}

	// Dedupe + 穩定排序便於 review diff
	seen := make(map[string]string)
	for _, e := range entries {
		key := e.city + "|" + e.li
		seen[key] = e.district
	}
	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString(`// Code generated by scripts/build_li_district. DO NOT EDIT.
// Source: 內政部 村里界 (dataset 7441).
// 雙北 (台北市 + 新北市) only.
package eco

func init() {
	liToDistrict = map[liKey]string{
`)
	for _, k := range keys {
		parts := strings.SplitN(k, "|", 2)
		city, li := parts[0], parts[1]
		fmt.Fprintf(&b, "\t{City: %q, Li: %q}: %q,\n", city, li, seen[k])
	}
	b.WriteString("\t}\n}\n")

	if err := os.WriteFile(*outPath, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", *outPath, err)
	}
	fmt.Printf("wrote %d (city,里) entries to %s\n", len(seen), *outPath)
}

func normalizeCity(s, traditional string) string {
	// traditional: "臺" 或 "台"
	if traditional == "臺" {
		return strings.ReplaceAll(s, "台", "臺")
	}
	return strings.ReplaceAll(s, "臺", "台")
}

func indexOf(row []string, name string) int {
	for i, h := range row {
		// 去掉 BOM 與前後空白
		clean := strings.TrimPrefix(strings.TrimSpace(h), "\ufeff")
		if clean == name {
			return i
		}
	}
	return -1
}

func readCSV(path string) ([][]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	r := csv.NewReader(f)
	r.FieldsPerRecord = -1 // tolerate ragged rows
	var rows [][]string
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		rows = append(rows, rec)
	}
	return rows, nil
}
